### ISSUE TITLE
How to run the example in Processing?

### ISSUE THREAD

**Issue by exotfboy** [micycle1/PGS#132]
> Download the latest PGS.jar from [releases](https://github.com/micycle1/PGS/releases) and simply drag-and-drop it onto the [Processing IDE](https://processing.org/environment).

Following the instruction, I tried to drop the `PGS-1.4.0` to processing ide, however it does not work. Seems like that only the text file are accepted.

**Comment by micycle1** [comment]
What exactly is not working? Are you dropping the .jar file?

**Comment by exotfboy** [comment]
Finally, I make it worked using the `Permanently` way. Thanks.
