### ISSUE TITLE
The function shapeIntersections(PShape, PShape) does not exist.

### ISSUE THREAD

**Issue by thierry75** [micycle1/PGS#18]
hi, thanks again for this library
two examples show errors:
voronoiCutOut line 68:  The function shapeIntersections(PShape, PShape) does not exist.
intersectionsBoids line 32: The function lineSegmentIntersections(List<PVector>) does not exist.

all others works well here (macos big sur -M1)

i think i will spend a lot of time with this (; 
i let you know if see something else
thanks

**Comment by thierry75** [comment]
<img width="713" alt="intersections" src="https://user-images.githubusercontent.com/372161/117376020-93246a80-aed0-11eb-8f01-436e8af8e6ad.png">
Strangely they appear in the auto-completion list

**Comment by micycle1** [comment]
Thanks for spotting this.

I renamed to methods slightly (e.g. from shapeIntersection**s**() to shapeIntersection()) but forgot to update the examples. Now fixed.
