### ISSUE TITLE
Readme request: link gifs to source code of each

### ISSUE THREAD

**Issue by hamoid** [micycle1/PGS#86]
Hi! Amazing collection of algorithms!! :)

An idea: I was thinking that it would be very nice if when clicking on one of the gifs or pngs it would jump to the source code of the program that created it (instead of linking to the original image file). 

Otherwise one may see something they would like to play with, but how to find the related code?

Cheers!

**Comment by micycle1** [comment]
Thank you for sharing your suggestion. 

This idea has actually been raised before, specifically in #44. In my response to that, I mentioned that while it could be useful, it might be considered overkill. My expectation is that the methods showcased in the GIFs should be easily discoverable within the codebase, usually by referring to the class relevant to section the GIF belongs to in the README file. Further, I've put a lot of effort into the javadocs, which should hopefully ease usage.

**Comment by hamoid** [comment]
Ok! :+1: I close this issue then :-)
